
version: "3"
services:
  mongodb:
    image: mongo:4-xenial
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    networks:
    - mongodb
    volumes:
    - mongodb-volume:/data/db

  mongodb-setup:
    image: mongo:4-xenial
    depends_on:
    - mongodb
    networks:
    - mongodb
    volumes:
    - ./scripts:/scripts
    entrypoint: ["sh", "/scripts/mongodb/initiate.sh"]

  mongodb-cves:
    image: mongo:4
    networks:
    - mongodb-cves
    restart: always
    volumes:
    - mongodb-cves-volume:/data/db

  sentinel-m3:
    image: registry.enginsight.com/enginsight/sentinel-m3:2.19.36
    networks:
    - redis
    - mongodb
    depends_on:
    - redis
    - mongodb
    - mongodb-setup
    restart: always
    volumes:
    - "./conf/services/config.json.production:/etc/enginsight/sentinel-m3/config.json"

  reporter-m4:
    image: registry.enginsight.com/enginsight/reporter-m4:1.18.55
    networks:
    - redis
    - mongodb
    - mongodb-cves
    depends_on:
    - redis
    - mongodb-setup
    - mongodb-cves
    restart: always
    volumes:
    - "./conf/services/config.json.production:/etc/enginsight/reporter-m4/config.json"

  profiler-m22:
    image: registry.enginsight.com/enginsight/profiler-m22:2.2.9
    networks:
    - redis
    - mongodb
    depends_on:
    - redis
    - mongodb
    - mongodb-setup
    restart: always
    volumes:
    - "./conf/services/config.json.production:/etc/enginsight/profiler-m22/config.json"

  anomalies-m28:
    image: registry.enginsight.com/enginsight/anomalies-m28:2.2.2
    networks:
    - redis
    - mongodb
    depends_on:
    - redis
    - mongodb
    - mongodb-setup
    restart: always
    volumes:
    - "./conf/services/config.json.production:/etc/enginsight/anomalies-m28/config.json"

  scheduler-m29:
    image: registry.enginsight.com/enginsight/scheduler-m29:1.5.10
    networks:
    - redis
    - mongodb
    depends_on:
    - redis
    - mongodb-setup
    restart: always
    volumes:
    - "./conf/services/config.json.production:/etc/enginsight/scheduler-m29/config.json"

  updater-m34:
    image: registry.enginsight.com/enginsight/updater-m34:2.0.4
    restart: always
    networks:
    - redis
    - mongodb
    depends_on:
    - redis
    - mongodb-setup
    volumes:
    - "./conf/services/config.json.production:/etc/enginsight/updater-m34/config.json"

  generator-m35:
    image: registry.enginsight.com/enginsight/generator-m35:1.12.29
    networks:
    - redis
    - mongodb
    depends_on:
    - redis
    - mongodb-setup
    restart: always
    volumes:
    - "./conf/services/config.json.production:/etc/enginsight/generator-m35/config.json"

  historian-m38:
    image: registry.enginsight.com/enginsight/historian-m38:2.1.35
    networks:
    - redis
    - mongodb
    depends_on:
    - redis
    - mongodb-setup
    restart: always
    volumes:
    - "./conf/services/config.json.production:/etc/enginsight/historian-m38/config.json"

  themis-m43:
    image: registry.enginsight.com/enginsight/themis-m43:1.16.4
    networks:
    - redis
    - mongodb
    depends_on:
    - redis
    - mongodb-setup
    restart: always
    volumes:
    - "./conf/services/config.json.production:/etc/enginsight/themis-m43/config.json"
  redis:
    image: redis:4-alpine
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]
    networks:
    - redis
    restart: always

networks:
  mongodb:
  redis:
  mongodb-cves:

volumes:
  mongodb-volume:
  mongodb-cves-volume:
